ba: ba.cpp
	g++ --std=c++11 ba.cpp dataio.cpp util.cpp -I /usr/include/eigen3/ -lpoplar -lpopops -lpoplin -lpoputil -ltbb -lboost_program_options -o ba

gbp: gbp.cpp
	g++ --std=c++11 gbp.cpp dataio.cpp util.cpp -I /usr/include/eigen3/ -lpoplar -lpopops -lpoplin -lpoputil -ltbb -lboost_program_options -o gbp


clean:
	rm -f gbp
	rm -f ba